name: On pull request push

on:
  pull_request:
    { types: [opened, edited, reopened, synchronize], branches: "*" }

jobs:
  pr-title-check:
    name: PR Title Check
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title format
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^(feat|fix|chore|ci)\\((frontend|backend|common|infra)\\): .+$"

  backend_linters:
    name: ‚öôÔ∏è Run backend Linters
    runs-on: ubuntu-latest
    needs: pr-title-check

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Python dependencies
        run: poetry install --no-root
        working-directory: backend

      - name: Run Pylint
        working-directory: backend
        run: poetry run pylint api

      - name: Run Black
        working-directory: backend
        run: poetry run black . --check

  backend_tests:
    name: üß™ Run Backend Tests
    runs-on: ubuntu-latest
    needs: pr-title-check

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Python dependencies
        run: poetry install --no-root --with dev
        working-directory: backend

      - name: Run unit tests
        working-directory: backend/api
        run: POSTGRES_HOST=localhost POSTGRES_DB_NAME=test_db POSTGRES_PORT=5432 POSTGRES_USER=user POSTGRES_PASSWORD=password poetry run pytest

  frontend-linters:
    name: ‚öôÔ∏è Run Frontend Linters
    runs-on: ubuntu-latest
    needs: pr-title-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint

      - name: Run Prettier
        working-directory: frontend
        run: npm run prettier:check

  frontend-tests:
    name: üß™ Run Frontend Tests
    runs-on: ubuntu-latest
    needs: pr-title-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run Tests
        working-directory: frontend
        run: npm run test
